=== richpeck/G6K/src/EUREKA/G6KBundle/Resources/data/databases/cout-certificat-immatriculation.schema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-04\/schema#",
    "type": "object",
    "title": "cout-certificat-immatriculation",
    "description": "Données de références pour le calcul du coût du cerficat d'immatriculation",
    "properties": {
        "baremeDemarche": {
            "type": "array",
            "title": "Barème par nature de démarche",
            "description": "Barème applicable selon la nature de la démarche",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:22, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "demarche": {
                        "type": "string",
                        "title": "Démarche [type:text]",
                        "description": "Libellé de la démarche"
                    },
                    "baremeMotoMoins125": {
                        "type": "number",
                        "title": "Barème moto (2 ou 3 roues) de moins de 125cm3 [type:number]",
                        "description": "Barème applicable à une moto (2 ou 3 roues) de moins de 125cm3 pour cette démarche",
                        "default": 0
                    },
                    "baremeAutre": {
                        "type": "number",
                        "title": "Barème autre véhicule [type:number]",
                        "description": "Barème applicable aux autres types de véhicule pour cette démarche",
                        "default": 0
                    }
                },
                "required": [
                    "id",
                    "demarche",
                    "baremeMotoMoins125",
                    "baremeAutre"
                ]
            }
        },
        "baremeVehicule": {
            "type": "array",
            "title": "Barème par type de véhicule",
            "description": "Barème applicable selon le type de véhicule",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:23, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "typeVehicule": {
                        "type": "string",
                        "title": "Type de véhicule [type:text]",
                        "description": "Type de véhicule"
                    },
                    "baremeMoins10": {
                        "type": "number",
                        "title": "Barème véhicule neuf ou moins de 10 ans [type:number]",
                        "description": "Barème applicable à un véhicule neuf ou de moins de 10 ans"
                    },
                    "baremePlus10": {
                        "type": "number",
                        "title": "Barème véhicule de plus de 10 ans [type:number]",
                        "description": "Barème applicable à un véhicule de plus de 10 ans"
                    },
                    "taxeFPTransport": {
                        "type": "number",
                        "title": "Taxe formation professionnelle dans les transports [type:money]",
                        "description": "Y2 - Taxe en euros sur la formation professionnelle dans les transports en fonction du PTAC"
                    }
                },
                "required": [
                    "id",
                    "typeVehicule",
                    "baremeMoins10",
                    "baremePlus10",
                    "taxeFPTransport"
                ]
            }
        },
        "malusCV": {
            "type": "array",
            "title": "Montants du malus selon la puissance fiscale",
            "description": "Montants du malus selon la puissance fiscale du véhicule et l'année d'achat",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:57, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "annee": {
                        "type": "integer",
                        "title": "Année d'achat du véhicule [type:year]",
                        "description": "Année d'achat du véhicule"
                    },
                    "minCV": {
                        "type": "integer",
                        "title": "Borne inférieure du nombre de CV [type:integer]",
                        "description": "Borne inférieure du nombre de CV fiscaux"
                    },
                    "maxCV": {
                        "type": "integer",
                        "title": "Borne supérieure du nombre de CV [type:integer]",
                        "description": "Borne supérieure du nombre de CV fiscaux"
                    },
                    "malus": {
                        "type": "number",
                        "title": "Montant du malus [type:money]",
                        "description": "Montant du malus en euros",
                        "default": 0
                    }
                },
                "required": [
                    "id",
                    "annee",
                    "minCV",
                    "maxCV",
                    "malus"
                ]
            }
        },
        "malusCO2": {
            "type": "array",
            "title": "Montants du malus selon le taux d'émission de CO2 par kilomètre",
            "description": "Montants du malus en fonction du nombre de grammes de CO2 émis par kilomètre et l'année d'achat",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:207, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "annee": {
                        "type": "integer",
                        "title": "Année d'achat du véhicule [type:year]",
                        "description": "Année d'achat du véhicule"
                    },
                    "minCO2": {
                        "type": "integer",
                        "title": "Borne inférieure du taux d'émission de CO2 [type:integer]",
                        "description": "Borne inférieure du nombre de grammes de CO2 émis par kilomètre"
                    },
                    "maxCO2": {
                        "type": "integer",
                        "title": "Borne supérieure du taux d'émission de CO2 [type:integer]",
                        "description": "Borne supérieure du nombre de grammes de CO2 émis par kilomètre"
                    },
                    "malus": {
                        "type": "number",
                        "title": "Montant du malus [type:money]",
                        "description": "Montant du malus en euros",
                        "default": 0
                    }
                },
                "required": [
                    "id",
                    "annee",
                    "minCO2",
                    "maxCO2",
                    "malus"
                ]
            }
        },
        "taxeAdditionnelleCO2": {
            "type": "array",
            "title": "Taxe additionnelle CO2",
            "description": "Taxe additionnelle CO2 en fonction du nombre de grammes de CO2 émis par kilomètre et l'année d'achat pour les véhicules ayant fait l'objet d'une réception communautaire",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:15, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "annee": {
                        "type": "integer",
                        "title": "Année d'achat du véhicule [type:year]",
                        "description": "Année d'achat du véhicule"
                    },
                    "tranche": {
                        "type": "integer",
                        "title": "Tranche du barême taxe additionnelle CO2 [type:integer]",
                        "description": "Tranche du barême taxe additionnelle CO2"
                    },
                    "minCO2": {
                        "type": "integer",
                        "title": "Borne inférieure du taux d'émission de CO2 [type:integer]",
                        "description": "Borne inférieure du nombre de grammes de CO2 émis par kilomètre"
                    },
                    "maxCO2": {
                        "type": "integer",
                        "title": "Borne supérieure du taux d'émission de CO2 [type:integer]",
                        "description": "Borne supérieure du nombre de grammes de CO2 émis par kilomètre"
                    },
                    "taxeParGramme": {
                        "type": "number",
                        "title": "Montant en euros de la taxe par gramme de CO2 [type:money]",
                        "description": "Montant en euros de la taxe par gramme de CO2 émis par kilomètre",
                        "default": 0
                    }
                },
                "required": [
                    "id",
                    "annee",
                    "tranche",
                    "minCO2",
                    "maxCO2",
                    "taxeParGramme"
                ]
            }
        },
        "taxeAdditionnelleCV": {
            "type": "array",
            "title": "Taxe additionnelle selon la puissance fiscale",
            "description": "Taxe additionnelle en fonction de la puissance fiscale et l'année d'achat pour les véhicules n'ayant pas fait l'objet d'une réception communautaire",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:19, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "annee": {
                        "type": "integer",
                        "title": "Année d'achat du véhicule [type:year]",
                        "description": "Année d'achat du véhicule"
                    },
                    "minCV": {
                        "type": "integer",
                        "title": "Borne inférieure du nombre de CV [type:integer]",
                        "description": "Borne inférieure du nombre de CV fiscaux"
                    },
                    "maxCV": {
                        "type": "integer",
                        "title": "Borne supérieure du nombre de CV [type:integer]",
                        "description": "Borne supérieure du nombre de CV fiscaux"
                    },
                    "taxe": {
                        "type": "number",
                        "title": "Montant en euros de la taxe [type:money]",
                        "description": "Montant en euros de la taxe",
                        "default": 0
                    }
                },
                "required": [
                    "id",
                    "annee",
                    "minCV",
                    "maxCV",
                    "taxe"
                ]
            }
        },
        "taxeRegionale": {
            "type": "array",
            "title": "Taxe régionale",
            "description": "Y1 - Taxe régionale pour 1 CV fiscal",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:31, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "regionId": {
                        "type": "integer",
                        "title": "Région [type:choice, datasource:cout-certificat-immatriculation, returnType:assocArray, valueColumn:codeRegion, labelColumn:name, request:select * from regions order by name]",
                        "description": "Identifiant de la région dans la table des régions"
                    },
                    "taxe": {
                        "type": "number",
                        "title": "Montant en euros de la taxe régionale [type:money]",
                        "description": "Montant en euros de la taxe pour 1 CV fiscal",
                        "default": 0
                    },
                    "exoVehiculePropre": {
                        "type": "number",
                        "title": "Pourcentage exonération véhicules propres [type:percent]",
                        "description": "Pourcentage d’exonération de la taxe régionale pour les véhicules propres"
                    }
                },
                "required": [
                    "id",
                    "regionId",
                    "taxe",
                    "exoVehiculePropre"
                ]
            }
        },
        "regions": {
            "type": "array",
            "title": "Régions",
            "description": "Régions",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:32, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "codeRegion": {
                        "type": "integer",
                        "title": "Code région [type:integer]",
                        "description": "Code de la région"
                    },
                    "name": {
                        "type": "string",
                        "title": "Nom de la région [type:text]",
                        "description": "Nom de la région"
                    }
                },
                "required": [
                    "id",
                    "codeRegion",
                    "name"
                ]
            }
        },
        "departements": {
            "type": "array",
            "title": "Départements",
            "description": "Départements",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:101, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "codeDep": {
                        "type": "string",
                        "title": "Code du département [type:department]",
                        "description": "Code du département"
                    },
                    "name": {
                        "type": "string",
                        "title": "Nom du département [type:text]",
                        "description": "Nom du département"
                    },
                    "regionId": {
                        "type": "integer",
                        "title": "Région [type:choice, datasource:cout-certificat-immatriculation, returnType:assocArray, valueColumn:codeRegion, labelColumn:name, request:select * from regions order by name]",
                        "description": "Identifiant de la région d'appartenance dans la table des régions"
                    }
                },
                "required": [
                    "id",
                    "codeDep",
                    "name",
                    "regionId"
                ]
            }
        },
        "energies": {
            "type": "array",
            "title": "Catégories énergétiques",
            "description": "Catégories énergétiques",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:15, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "energie": {
                        "type": "string",
                        "title": "Energie [type:text]",
                        "description": "Libellé énergie"
                    },
                    "pourcentMalusCO2": {
                        "type": "number",
                        "title": "Pourcentage sur le taux CO2 [type:percent]",
                        "description": "Pourcentage sur le taux CO2"
                    },
                    "pourcentTaxeAdditionnelle": {
                        "type": "number",
                        "title": "Pourcentage de la taxe additionnelle [type:percent]",
                        "description": "Pourcentage de la taxe additionnelle"
                    },
                    "energiePropre": {
                        "type": "boolean",
                        "title": "Energie propre ? [type:boolean]",
                        "description": "Energie propre permettant une exonération totale ou partielle de la taxe régionale"
                    }
                },
                "required": [
                    "id",
                    "energie",
                    "pourcentMalusCO2",
                    "pourcentTaxeAdditionnelle",
                    "energiePropre"
                ]
            }
        },
        "prelevementadditionnel": {
            "type": "array",
            "title": "prelevementadditionnel",
            "description": "<p>Prélèvement additionnel grosse cylindrée<\/p>",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "title": "id [primarykey:1, autoincrement:51, type:integer]",
                        "description": "Identifiant interne"
                    },
                    "annee": {
                        "type": "integer",
                        "title": "Année de la démarche [type:year]",
                        "description": ""
                    },
                    "borneinf": {
                        "type": "integer",
                        "title": "borne inférieure [type:integer]",
                        "description": ""
                    },
                    "bornesup": {
                        "type": "integer",
                        "title": "borne supérieure [type:integer]",
                        "description": ""
                    },
                    "montantCV": {
                        "type": "number",
                        "title": "montant par CV [type:money]",
                        "description": ""
                    }
                },
                "required": [
                    "id",
                    "annee",
                    "borneinf",
                    "bornesup",
                    "montantCV"
                ]
            }
        }
    },
    "required": [
        "baremeDemarche",
        "baremeVehicule",
        "malusCV",
        "malusCO2",
        "taxeAdditionnelleCO2",
        "taxeAdditionnelleCV",
        "taxeRegionale",
        "regions",
        "departements",
        "energies",
        "prelevementadditionnel"
    ]
}

=== richpeck/G6K/src/EUREKA/G6KBundle/Resources/data/databases/cout-certificat-immatriculation.json
{
    "baremeDemarche": [
        {
            "id": 1,
            "demarche": "Première immatriculation en France d'un véhicule",
            "baremeMotoMoins125": 0.5,
            "baremeAutre": 1
        },
        {
            "id": 2,
            "demarche": "Immatriculation d’un véhicule d’occasion (changement de titulaire du certificat)",
            "baremeMotoMoins125": 0.5,
            "baremeAutre": 1
        },
        {
            "id": 3,
            "demarche": "Duplicata - véhicule SIV (immatriculation type \"AB-123-CD\")",
            "baremeMotoMoins125": 0.25,
            "baremeAutre": 1
        },
        {
            "id": 4,
            "demarche": "Duplicata - véhicule FNI  (ancienne immatriculation de type \"1234 AB 01\")",
            "baremeMotoMoins125": 0,
            "baremeAutre": 0
        },
        {
            "id": 5,
            "demarche": "Changement d'adresse",
            "baremeMotoMoins125": 0,
            "baremeAutre": 0
        },
        {
            "id": 6,
            "demarche": "Changement d'état matrimonial (mariage, divorce, veuvage)",
            "baremeMotoMoins125": 0,
            "baremeAutre": 0
        },
        {
            "id": 7,
            "demarche": "Correction d'erreur de saisie sur le certificat du fait de l'administration",
            "baremeMotoMoins125": 0,
            "baremeAutre": 0
        },
        {
            "id": 8,
            "demarche": "Usurpation du numéro d'immatriculation du véhicule",
            "baremeMotoMoins125": 0,
            "baremeAutre": 0
        },
        {
            "id": 9,
            "demarche": "Utilisation de toutes les cases réservées pour les contrôles techniques",
            "baremeMotoMoins125": 0,
            "baremeAutre": 0
        },
        {
            "id": 10,
            "demarche": "Modification des caractéristiques techniques du véhicule",
            "baremeMotoMoins125": 0.25,
            "baremeAutre": 1
        },
        {
            "id": 11,
            "demarche": "Modification de l'usage du véhicule",
            "baremeMotoMoins125": 0.25,
            "baremeAutre": 1
        },
        {
            "id": 12,
            "demarche": "Changement d'état civil",
            "baremeMotoMoins125": 0.25,
            "baremeAutre": 1
        },
        {
            "id": 13,
            "demarche": "Changement de dénomination sociale d'une entreprise ou d'une association",
            "baremeMotoMoins125": 0.25,
            "baremeAutre": 1
        },
        {
            "id": 14,
            "demarche": "Certificat W garage",
            "baremeMotoMoins125": 2,
            "baremeAutre": 2
        },
        {
            "id": 15,
            "demarche": "Passage en véhicule de collection",
            "baremeMotoMoins125": 0.25,
            "baremeAutre": 1
        },
        {
            "id": 16,
            "demarche": "Héritage (hors veuvage) d'un véhicule",
            "baremeMotoMoins125": 0.5,
            "baremeAutre": 1
        },
        {
            "id": 17,
            "demarche": "Achat par locataire suite leasing",
            "baremeMotoMoins125": 0.5,
            "baremeAutre": 1
        },
        {
            "id": 18,
            "demarche": "Ajout d'un autre propriétaire (sauf conjoint)",
            "baremeMotoMoins125": 0.5,
            "baremeAutre": 1
        },
        {
            "id": 19,
            "demarche": "Certificat WW",
            "baremeMotoMoins125": 1,
            "baremeAutre": 1
        },
        {
            "id": 20,
            "demarche": "Série TT",
            "baremeMotoMoins125": 1.5,
            "baremeAutre": 1.5
        },
        {
            "id": 21,
            "demarche": "Véhicule acquis en remplacement d'un véhicule détruit lors d'une catastrophe naturelle\n",
            "baremeMotoMoins125": 0,
            "baremeAutre": 0
        },
        {
            "id": 22,
            "demarche": "Demande de duplicata d'un certificat détruit lors d'une catastrophe naturelle",
            "baremeMotoMoins125": 0,
            "baremeAutre": 0
        }
    ],
    "baremeVehicule": [
        {
            "id": 1,
            "typeVehicule": "Voiture particulière (VP)",
            "baremeMoins10": 1,
            "baremePlus10": 0.5,
            "taxeFPTransport": 0
        },
        {
            "id": 2,
            "typeVehicule": "Camionnette (CTTE)",
            "baremeMoins10": 1,
            "baremePlus10": 0.5,
            "taxeFPTransport": 34
        },
        {
            "id": 3,
            "typeVehicule": "Camping-car et autre véhicule VASP (PTAC égal à ou moins de 3,5 tonnes)",
            "baremeMoins10": 1,
            "baremePlus10": 0.5,
            "taxeFPTransport": 0
        },
        {
            "id": 4,
            "typeVehicule": "Camping-car et autre véhicule VASP (PTAC supérieur à 3,5 tonnes)",
            "baremeMoins10": 0.5,
            "baremePlus10": 0.25,
            "taxeFPTransport": 0
        },
        {
            "id": 5,
            "typeVehicule": "Moto jusqu'à 125 cm3 (MTL)",
            "baremeMoins10": 0.5,
            "baremePlus10": 0.25,
            "taxeFPTransport": 0
        },
        {
            "id": 6,
            "typeVehicule": "Moto de plus de 125 cm3 (MTT1 \/ MTT2)",
            "baremeMoins10": 0.5,
            "baremePlus10": 0.25,
            "taxeFPTransport": 0
        },
        {
            "id": 7,
            "typeVehicule": "Tricycle à moteur (TM)",
            "baremeMoins10": 1,
            "baremePlus10": 0.5,
            "taxeFPTransport": 0
        },
        {
            "id": 8,
            "typeVehicule": "Quadricycle à moteur (QM)",
            "baremeMoins10": 1,
            "baremePlus10": 0.5,
            "taxeFPTransport": 0
        },
        {
            "id": 9,
            "typeVehicule": "Cyclomoteur à 3 roues (CYCL)",
            "baremeMoins10": 1,
            "baremePlus10": 0.5,
            "taxeFPTransport": 0
        },
        {
            "id": 10,
            "typeVehicule": "Cyclomoteur à 2 roues ou à 3 roues (inférieur ou égal à 50 cm3) non carrossé (CL)",
            "baremeMoins10": 0,
            "baremePlus10": 0,
            "taxeFPTransport": 0
        },
        {
            "id": 11,
            "typeVehicule": "Camion d'un PTAC supérieur à 3,5 tonnes et inférieur à 6 tonnes (CAM)",
            "baremeMoins10": 0.5,
            "baremePlus10": 0.25,
            "taxeFPTransport": 127
        },
        {
            "id": 12,
            "typeVehicule": "Camion d'un PTAC supérieur ou égal à 6 tonnes et inférieur à 11 tonnes (CAM)",
            "baremeMoins10": 0.5,
            "baremePlus10": 0.25,
            "taxeFPTransport": 189
        },
        {
            "id": 13,
            "typeVehicule": "Camion d'un PTAC supérieur ou égal à 11 tonnes (CAM)",
            "baremeMoins10": 0.5,
            "baremePlus10": 0.25,
            "taxeFPTransport": 285
        },
        {
            "id": 14,
            "typeVehicule": "Véhicule de transport en commun d'un PTAC inférieur ou égal à 3,5 tonnes (TCP)",
            "baremeMoins10": 1,
            "baremePlus10": 0.5,
            "taxeFPTransport": 285
        },
        {
            "id": 15,
            "typeVehicule": "Véhicule de transport en commun d'un PTAC supérieur à 3,5 tonnes (TCP)",
            "baremeMoins10": 0.5,
            "baremePlus10": 0.25,
            "taxeFPTransport": 285
        },
        {
            "id": 16,
            "typeVehicule": "Tracteur routier (TRR)",
            "baremeMoins10": 0.5,
            "baremePlus10": 0.25,
            "taxeFPTransport": 285
        },
        {
            "id": 17,
            "typeVehicule": "Véhicule agricole (TRA \/ MAGA)",
            "baremeMoins10": 1.5,
            "baremePlus10": 1.5,
            "taxeFPTransport": 0
        },
        {
            "id": 18,
            "typeVehicule": "Remorque ou semi-remorque agricole ou non-agricole (SRAT \/ SREM \/ REM \/ SRTC \/ RETC \/ SRSP \/ RESP \/ REA \/ SREA \/ MIAR)",
            "baremeMoins10": 1.5,
            "baremePlus10": 1.5,
            "taxeFPTransport": 0
        },
        {
            "id": 23,
            "typeVehicule": "Caravane tractée (genre RESP)",
            "baremeMoins10": 1.5,
            "baremePlus10": 1.5,
            "taxeFPTransport": 0
        }
    ],
    "malusCV": [
        {
            "id": 1,
            "annee": 2008,
            "minCV": 0,
            "maxCV": 7,
            "malus": 0
        },
        {
            "id": 2,
            "annee": 2008,
            "minCV": 8,
            "maxCV": 11,
            "malus": 750
        },
        {
            "id": 3,
            "annee": 2008,
            "minCV": 12,
            "maxCV": 16,
            "malus": 1600
        },
        {
            "id": 4,
            "annee": 2008,
            "minCV": 17,
            "maxCV": 99,
            "malus": 2600
        },
        {
            "id": 5,
            "annee": 2009,
            "minCV": 0,
            "maxCV": 7,
            "malus": 0
        },
        {
            "id": 6,
            "annee": 2009,
            "minCV": 8,
            "maxCV": 11,
            "malus": 750
        },
        {
            "id": 7,
            "annee": 2009,
            "minCV": 12,
            "maxCV": 16,
            "malus": 1600
        },
        {
            "id": 8,
            "annee": 2009,
            "minCV": 17,
            "maxCV": 99,
            "malus": 2600
        },
        {
            "id": 9,
            "annee": 2010,
            "minCV": 0,
            "maxCV": 7,
            "malus": 0
        },
        {
            "id": 10,
            "annee": 2010,
            "minCV": 8,
            "maxCV": 11,
            "malus": 750
        },
        {
            "id": 11,
            "annee": 2010,
            "minCV": 12,
